version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_SPOONACULAR_API_KEY=ecc0e22681cd4d4780e6b6aa17d4400d
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://kjbryant44:Raiderbryant1010@veganrecipe.ctmyv30.mongodb.net/?retryWrites=true&w=majority&appName=VeganRecipe
      - SPOONACULAR_API_KEY=ecc0e22681cd4d4780e6b6aa17d4400d
      - SESSION_SECRET=KB123454321RB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge